### ISSUE TITLE
No edit access [FIXED]

### ISSUE THREAD

**Issue by NTBeta** [SuperGemProd/captain-gem#1]
I can’t edit the files lol

**Comment by NTBeta** [comment]
I think you need to give me and Nick owner too

**Comment by shinkintoad** [comment]
xdddddddddddddd whoops

**Comment by shinkintoad** [comment]
Sorry, i'll fix that now.

**Comment by shinkintoad** [comment]
Should be fixed. Lmk if not, @NTBeta.

**Comment by shinkintoad** [comment]
I can almost guarantee it is fixed, if it is not, re-open this issue. Else, I am now closing this issue. Thanks for bringing it to my attention.
