### ISSUE TITLE
Playing the game [DOCUMENTATION]

### ISSUE THREAD

**Issue by shinkintoad** [SuperGemProd/captain-gem#2]
# I consider this more so documentation, but eh.

To play Captain Gem, you will need to run the files in the `game` folder. Running these types of files is easy, and you should be able to figure it out. If not, [join our Discord server](https://discordapp.com/invite/b5YQYqVxTG) for assistance, or [Google](https://google.com/) it.

**Comment by 77Spades** [comment]
bruh
